### ISSUE TITLE
Current Date is not using the correct timezone

### ISSUE THREAD

**Issue by larizzatg** [DannyFeliz/vue-timed-content#47]
The component doesn't convert the current date to the correct timezone. 
```html
    <timed-content
      :from="new Date('2020/09/18 16:00:00')"
      :to="new Date('2020/09/18 16:59:59')"
      time-zone="America/Los_Angeles"
    >
      <p>Test timed content</p>
    </timed-content>
```

It doesn't show the component because the comparison is being made with the current date without the timezone.

**Comment by vyzaldysanchez** [comment]
A PR was submitted to solve this issue, now the current date within the component should be pointing to the correct timezone.

**Comment by DannyFeliz** [comment]
Yeah, missed that, @vyzaldysanchez has a PR for this issue. I'm going to release a new version.

Let us know if this fixes your issue.
