### ISSUE TITLE
Only dispatch the show event if the content initially was hidden

### ISSUE THREAD

**Issue by DannyFeliz** [DannyFeliz/vue-timed-content#8]
To avoid spamming events we should only dispatch the `show` event if the content was hidden before. The intention behind this is to only inform when the content started to show instead of inform if the content is currently showing.

The same should with the `hide` event, only dispatch it if content was showing previously.

**Comment by vyzaldysanchez** [comment]
Added #10 as an attempt to solve this issue @DannyFeliz
